### ISSUE TITLE
Can't open popup window if `ambiwidth=double` is set

### ISSUE THREAD

**Issue by sakuraiyuta** [skanehira/denops-translate.vim#66]
https://github.com/skanehira/denops-translate.vim/blob/68a034a6f3f2e838c31e4c60582e03ecc0aad2b0/autoload/translate.vim#L85-L88

The border setting causes an error:
`Vim(let):E5555: API call: border chars must be one cell`

## reproduce
`set ambiwidth=double` and exec `:Translate`

https://github.com/skanehira/denops-translate.vim/assets/378747/d6391cba-4961-4b8b-af70-028ca2450e83

**Comment by skanehira** [comment]
@sakuraiyuta Sorry about late.
I add option `g:translate_border_chars` that can change border chars.
You can set valid chars when using ambiwidth is double

**Comment by sakuraiyuta** [comment]
LGTM

![image](https://github.com/skanehira/denops-translate.vim/assets/378747/f2a90db6-247a-4e50-9766-6f08e977d78e)

My settings:

```vim
let g:translate_border_chars=['+', '-', '+', '|', '+', '-', '+', '|']
```

Thank you!

**Comment by mimikun** [comment]
I have same issue too.
Thanks @sakuraiyuta, your solution solved it for me.
